// <auto-generated />
using System;
using Kahia2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kahia2.Migrations
{
    [DbContext(typeof(Kahia2Context))]
    partial class Kahia2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kahia2.Models.Patho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomPatho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patho");
                });

            modelBuilder.Entity("Kahia2.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("GroupeSanguin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Patho1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Patho2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Patho3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Patho4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Patho5Id")
                        .HasColumnType("int");

                    b.Property<int>("Poids")
                        .HasColumnType("int");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SituationMatrimoniale")
                        .HasColumnType("bit");

                    b.Property<int>("Taille")
                        .HasColumnType("int");

                    b.HasKey("IdPatient");

                    b.HasIndex("Patho1Id");

                    b.HasIndex("Patho2Id");

                    b.HasIndex("Patho3Id");

                    b.HasIndex("Patho4Id");

                    b.HasIndex("Patho5Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Kahia2.Models.Patient", b =>
                {
                    b.HasOne("Kahia2.Models.Patho", "Patho1")
                        .WithMany()
                        .HasForeignKey("Patho1Id");

                    b.HasOne("Kahia2.Models.Patho", "Patho2")
                        .WithMany()
                        .HasForeignKey("Patho2Id");

                    b.HasOne("Kahia2.Models.Patho", "Patho3")
                        .WithMany()
                        .HasForeignKey("Patho3Id");

                    b.HasOne("Kahia2.Models.Patho", "Patho4")
                        .WithMany()
                        .HasForeignKey("Patho4Id");

                    b.HasOne("Kahia2.Models.Patho", "Patho5")
                        .WithMany()
                        .HasForeignKey("Patho5Id");
                });
#pragma warning restore 612, 618
        }
    }
}
